[package]
name = "may_minihttp"
version = "0.1.0"
edition = "2018"
authors = ["Xudong Huang <huangxu008@hotmail.com>"]
license = "MIT/Apache-2.0"

[dependencies]
may = "0.3"
log = "0.4"
itoa = "1"
bytes = "1"
httparse = "1"
lazy_static = "1"
time = { version = "0.3", features = ["formatting"] }

[dev-dependencies]
mimalloc = "0.1"
num_cpus = "1.0"
oorandom = "11"
smallvec = "1.1"
env_logger = "0.9"
serde_json = "1"
yarte = { version = "0.15", features = ["bytes-buf", "json"] }
may_postgres = { git = "https://github.com/Xudong-Huang/may_postgres.git" }

[profile.release]
lto = true
opt-level = 3
codegen-units = 1